### ISSUE TITLE
Fails to build with openssl 1.1.0

### ISSUE THREAD

**Issue by Ampelbein** [nzbget/nzbget#298]
Hi,

when building against the most recent openssl library (1.1.0b), the configure script fails to find openssl and  (since the gnutls libraries aren't installed either) dies:

```
checking whether to use TLS/SSL... yes
checking for openssl... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing CRYPTO_set_locking_callback... no
checking for gnutls... no
configure: error: Package requirements (gnutls) were not met:

No package 'gnutls' found
[...]
configure:7731: g++ -o conftest -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/nzbget-17.1+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include/libxml2 -D_GNU_
SOURCE -D_DEFAULT_SOURCE  -Wl,-z,relro conftest.cpp -lcrypto  -lpthread  -lxml2 -lncurses -ltinfo -lssl -lcrypto >&5
/tmp/ccFuyD2D.o: In function `main':
./conftest.cpp:46: undefined reference to `CRYPTO_set_locking_callback'
collect2: error: ld returned 1 exit status
```

Please consider adding support for openssl1.1.0, thank you!
