### PR TITLE
Fixed compilation error with g++ 5.3

### PR DESCRIPTION
**Pull request by parnic**
```
daemon/connect/TlsSocket.cpp: In member function ‘bool TlsSocket::Start()’:
daemon/connect/TlsSocket.cpp:322:56: error: use of deleted function ‘CString::CString(CString&)’
  const char* priority = !m_cipher.Empty() ? m_cipher : "NORMAL";
                                                        ^
In file included from daemon/connect/TlsSocket.h:30:0,
                 from daemon/connect/TlsSocket.cpp:30:
./daemon/util/NString.h:73:2: note: declared here
  CString(CString& other) = delete;
  ^
```

### CODE REVIEW

**Comment by hugbug** [comment]
Strange that it works for me.
- What is your exact compiler version? Mine is 5.3.0.

I'd like to reproduce the problem in order to being able to detect and fix such cases myself in the future. Currently I compile with GCC 4.8.2, GCC 5.2, GCC 5.3, clang (version for Xcode on Mac) and MS VS 2015. All of them work.
- Can you please post the full output of compiler and your config.log (via pastern.com); I'd like to compare compiling options.
- What platform you compile on and for?
- Have you build the compiler yourself or does it come with your OS?

**Comment by parnic** [comment]
> What is your exact compiler version? Mine is 5.3.0.

```
nzbget@orion:~/nzbget$ g++ --version
g++ (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

> Can you please post the full output of compiler and your config.log (via pastern.com); I'd like to compare compiling options.

`make` output: http://pastebin.com/YP7vvFax
[config.log.txt](https://github.com/nzbget/nzbget/files/75933/config.log.txt)

> What platform you compile on and for?

Ubuntu 14.04 x86_64

```
$ uname -a
Linux orion 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

> Have you build the compiler yourself or does it come with your OS?

I use the g++-5 apt package from Ubuntu's Test PPA (http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/) since the default PPAs only provide GCC 4.8 or something and I use c++14 features in another project I work on.

**Comment by hugbug** [comment]
Spent hours compiling different gcc versions without any luck to reproduce the problem, only to realize at the end that the problem is in GnuTLS related code whereas I compile with OpenSSL :smile:
